name: course_5
on: [ push ]
jobs:



  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: cp to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          source: 'docker-compose.yaml'
          target: "course_5"
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          script: |
            cd course_5
            echo ${{ secrets.password }} | sudo -S docker-compose up -d